In [2]:
import numpy as np

# 1. Convert List to 1D Array
original_list = [12.23, 13.32, 100, 36.32]
array_1d = np.array(original_list)
print("1. One-dimensional NumPy array:", array_1d)

# 2. Create 3x3 Matrix (2–10)
matrix_3x3 = np.arange(2, 11).reshape(3, 3)
print("\n2. 3x3 Matrix from 2 to 10:\n", matrix_3x3)

# 3. Null Vector (10) & Update Sixth Value
null_vector = np.zeros(10)
print("\n3. Null Vector:", null_vector)
null_vector[6] = 11
print("Updated Vector:", null_vector)

# 4. Array from 12 to 38
range_array = np.arange(12, 38)
print("\n4. Array from 12 to 38:\n", range_array)

# 5. Convert Array to Float Type
int_array = np.array([1, 2, 3, 4])
float_array = int_array.astype(float)
print("\n5. Array converted to float:", float_array)

# 6. Celsius to Fahrenheit Conversion
celsius = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0.])
fahrenheit = celsius * 9 / 5 + 32
print("\n6. Values in Centigrade degrees:", celsius)
print("Values in Fahrenheit degrees:", fahrenheit)

# 7. Append Values to Array (Do self-study)
original_array = np.array([10, 20, 30])
appended_array = np.append(original_array, [40, 50, 60, 70, 80, 90])
print("\n7. After appending values:", appended_array)

# 8. Array Statistical Functions (Do self-study)
random_array = np.random.rand(10)
mean_val = np.mean(random_array)
median_val = np.median(random_array)
std_dev = np.std(random_array)
print("\n8. Random Array:", random_array)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)

# 9. Find min and max in 10x10 array
array_10x10 = np.random.rand(10, 10)
min_val = np.min(array_10x10)
max_val = np.max(array_10x10)
print("\n9. 10x10 Random Array:\n", array_10x10)
print("Minimum:", min_val)
print("Maximum:", max_val)

# 10. Create a 3x3x3 array with random values
array_3x3x3 = np.random.rand(3, 3, 3)
print("\n10. 3x3x3 Random Array:\n", array_3x3x3)


1. One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]

2. 3x3 Matrix from 2 to 10:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

3. Null Vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated Vector: [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]

4. Array from 12 to 38:
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]

5. Array converted to float: [1. 2. 3. 4.]

6. Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Fahrenheit degrees: [-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]

7. After appending values: [10 20 30 40 50 60 70 80 90]

8. Random Array: [0.58796645 0.57757185 0.53297145 0.8536238  0.01963669 0.93984267
 0.1189282  0.19887418 0.24379133 0.1958731 ]
Mean: 0.42690797040520023
Median: 0.3883813866124517
Standard Deviation: 0.30078347309379483

9. 10x10 Random Array:
 [[0.15536567 0.96846305 0.75955834 0.33987032 0.12006329 0.08841054
  0.59877439 0.27810019 0.8331238  0.21352254]
 [0.154535