In [1]:
import numpy as np

array_3x3x3 = np.random.rand(3, 3, 3)
print("Random 3x3x3 Array:\n", array_3x3x3)

Random 3x3x3 Array:
 [[[0.01954558 0.54951183 0.65973245]
  [0.38436379 0.27923884 0.16932023]
  [0.90905555 0.55442501 0.10238481]]

 [[0.19525724 0.5363814  0.64014767]
  [0.98952424 0.65090867 0.05313573]
  [0.72177575 0.57478571 0.85819826]]

 [[0.86685392 0.20027312 0.74354619]
  [0.99575565 0.17335493 0.41766454]
  [0.42846309 0.72699732 0.62267327]]]


In [2]:
import pandas as pd
import numpy as np

data = {
    'First Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)

df.columns = [col.lower().replace(" ", "_") for col in df.columns]

print("First 3 rows:\n", df.head(3))

print("Mean Age:", df['age'].mean())

print("Selected Columns:\n", df[['first_name', 'city']])

df['salary'] = np.random.randint(40000, 100000, size=len(df))

print("Summary Statistics:\n", df.describe(include='all'))

First 3 rows:
   first_name  age           city
0      Alice   25       New York
1        Bob   30  San Francisco
2    Charlie   35    Los Angeles
Mean Age: 32.5
Selected Columns:
   first_name           city
0      Alice       New York
1        Bob  San Francisco
2    Charlie    Los Angeles
3      David        Chicago
Summary Statistics:
        first_name        age      city        salary
count           4   4.000000         4      4.000000
unique          4        NaN         4           NaN
top         Alice        NaN  New York           NaN
freq            1        NaN         1           NaN
mean          NaN  32.500000       NaN  80787.000000
std           NaN   6.454972       NaN   9992.536715
min           NaN  25.000000       NaN  69934.000000
25%           NaN  28.750000       NaN  76769.500000
50%           NaN  32.500000       NaN  79539.500000
75%           NaN  36.250000       NaN  83557.000000
max           NaN  40.000000       NaN  94135.000000


In [13]:
import requests

API_KEY = "131ef48faf4bcf0b4dacd0545d308087"  
city = "Tashkent"
url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"

response = requests.get(url)
data = response.json()

if response.status_code == 200:
    print("City:", data["name"])
    print("Temperature:", data["main"]["temp"], "°C")
    print("Humidity:", data["main"]["humidity"], "%")
    print("Weather:", data["weather"][0]["description"])
else:
    print("Error fetching data:", data.get("message", "Unknown error"))

City: Tashkent
Temperature: 29.59 °C
Humidity: 16 %
Weather: scattered clouds


In [5]:
import numpy as np

original_array = np.array([10, 20, 30])
values_to_append = [40, 50, 60, 70, 80, 90]

new_array = np.append(original_array, values_to_append)

print("Original array:", original_array)
print("After append values to the end of the array:", new_array)

Original array: [10 20 30]
After append values to the end of the array: [10 20 30 40 50 60 70 80 90]


In [22]:
import json
import requests
import random

API_KEY = "8f8a91c4"  
BASE_URL = "http://www.omdbapi.com/?i=tt3896198&apikey=8f8a91c4"

movie_data = {
    "Title": "Guardians of the Galaxy Vol. 2",
    "Year": "2017",
    "Rated": "PG-13",
    "Released": "05 May 2017",
    "Runtime": "136 min",
    "Genre": "Action, Adventure, Comedy",
    "Director": "James Gunn",
    "Writer": "James Gunn, Dan Abnett, Andy Lanning",
    "Actors": "Chris Pratt, Zoe Saldaña, Dave Bautista",
    "Plot": "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father, the ambitious celestial being Ego.",
    "Language": "English",
    "Country": "United States",
    "Awards": "Nominated for 1 Oscar. 15 wins & 60 nominations total",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNWE5MGI3MDctMmU5Ni00YzI2LWEzMTQtZGIyZDA5MzQzNDBhXkEyXkFqcGc@._V1_SX300.jpg",
    "Ratings": [
        {"Source": "Internet Movie Database", "Value": "7.6/10"},
        {"Source": "Rotten Tomatoes", "Value": "85%"},
        {"Source": "Metacritic", "Value": "67/100"}
    ],
    "Metascore": "67",
    "imdbRating": "7.6",
    "imdbVotes": "792,363",
    "imdbID": "tt3896198",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "$389,813,101",
    "Production": "N/A",
    "Website": "N/A",
    "Response": "True"
}

if genre not in genre_movies:
    print("Sorry, genre not supported.")
else:
    movie_title = random.choice(genre_movies[genre])
    params = {"t": movie_title, "apikey": API_KEY}
    response = requests.get(BASE_URL, params=params)
    data = response.json()

    if data["Response"] == "True":
        print(f"\nMovie Recommendation ({genre.capitalize()})")
        print("Title:", data["Title"])
        print("Year:", data["Year"])
        print("Genre:", data["Genre"])
        print("Rated:", movie_data["Rated"])
        print("Released:", movie_data["Released"])
        print("Runtime:", movie_data["Runtime"])
        print("Director:", movie_data["Director"])
        print("Writer:", movie_data["Writer"])
        print("Actors:", movie_data["Actors"])
        print("Plot:", data["Plot"])
        print("Language:", movie_data["Language"])
        print("Country:", movie_data["Country"]) 
        print("IMDB Rating:", data["imdbRating"])
        print("Box Office Collection:", movie_data["BoxOffice"])
        print("Awards:", movie_data["Awards"])
        print("Ratings:")

    for rating in movie_data["Ratings"]:
        print(f"  - {rating['Source']}: {rating['Value']}")

    else:
        print("Movie not found.")

    

  - Internet Movie Database: 7.6/10
  - Rotten Tomatoes: 85%
  - Metacritic: 67/100
Movie not found.
